<!DOCTYPE html>
<html lang=en>
<head>
    <meta charset=utf-8>
    <meta http-equiv=X-UA-Compatible content="IE=edge">
    <meta name=viewport content="width=device-width,initial-scale=1">
    <link rel=icon href=/favicon.ico>
    <title>pure-book-view</title>
    <link href=/static/dist/css/app.a8192ce4.css rel=preload as=style>
    <link href=/static/dist/css/chunk-vendors.39a2421b.css rel=preload as=style>
    <link href=/static/dist/js/app.82270983.js rel=preload as=script>
    <link href=/static/dist/js/chunk-vendors.d106f963.js rel=preload as=script>
    <link href=/static/dist/css/chunk-vendors.39a2421b.css rel=stylesheet>
    <link href=/static/dist/css/app.a8192ce4.css rel=stylesheet>
</head>
<body>
<noscript><strong>We're sorry but pure-book-view doesn't work properly without JavaScript enabled. Please enable it to
    continue.</strong></noscript>
<div id=app></div>
<script src=/static/dist/js/chunk-vendors.d106f963.js></script>
<script src=/static/dist/js/app.82270983.js></script>
</body>
</html>